name: Danger

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

env:
  BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile.danger

jobs:
  danger:
    uses: numbata/danger-pr-comment/.github/workflows/danger-run.yml@v0.1.0
    secrets: inherit
    with:
      ruby-version: '3.3'
      bundler-cache: true
